package leetcode.findtheDifference;

import java.util.*;
import java.util.stream.*;
import java.util.function.*;
import leetcode.*;

/**
 * 
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
 * 

 * Source: https://leetcode.com/problems/find-the-difference/
 */
public class Solution {
    public char findTheDifference(String s, String t) {
        int[] xor = {0};
        Arrays.asList(t, s).forEach(v -> v.chars().forEach(c -> xor[0] ^= c));
        return (char) xor[0];
    }
}
